package br.com.testes.mybatis.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import br.com.testes.mybatis.model.Cliente;
import br.com.testes.mybatis.model.ClienteExample.Criteria;
import br.com.testes.mybatis.model.ClienteExample.Criterion;
import br.com.testes.mybatis.model.ClienteExample;
import java.util.List;
import java.util.Map;

public class ClienteSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String countByExample(ClienteExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("cliente");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String deleteByExample(ClienteExample example) {
        BEGIN();
        DELETE_FROM("cliente");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String insertSelective(Cliente record) {
        BEGIN();
        INSERT_INTO("cliente");
        
        if (record.getIdcliente() != null) {
            VALUES("idcliente", "#{idcliente,jdbcType=INTEGER}");
        }
        
        if (record.getNome() != null) {
            VALUES("nome", "#{nome,jdbcType=VARCHAR}");
        }
        
        if (record.getTelefone() != null) {
            VALUES("telefone", "#{telefone,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String selectByExample(ClienteExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("idcliente");
        } else {
            SELECT("idcliente");
        }
        SELECT("nome");
        SELECT("telefone");
        FROM("cliente");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Cliente record = (Cliente) parameter.get("record");
        ClienteExample example = (ClienteExample) parameter.get("example");
        
        BEGIN();
        UPDATE("cliente");
        
        if (record.getIdcliente() != null) {
            SET("idcliente = #{record.idcliente,jdbcType=INTEGER}");
        }
        
        if (record.getNome() != null) {
            SET("nome = #{record.nome,jdbcType=VARCHAR}");
        }
        
        if (record.getTelefone() != null) {
            SET("telefone = #{record.telefone,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("cliente");
        
        SET("idcliente = #{record.idcliente,jdbcType=INTEGER}");
        SET("nome = #{record.nome,jdbcType=VARCHAR}");
        SET("telefone = #{record.telefone,jdbcType=VARCHAR}");
        
        ClienteExample example = (ClienteExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String updateByPrimaryKeySelective(Cliente record) {
        BEGIN();
        UPDATE("cliente");
        
        if (record.getNome() != null) {
            SET("nome = #{nome,jdbcType=VARCHAR}");
        }
        
        if (record.getTelefone() != null) {
            SET("telefone = #{telefone,jdbcType=VARCHAR}");
        }
        
        WHERE("idcliente = #{idcliente,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    protected void applyWhere(ClienteExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}