package br.com.testes.mybatis.dao;

import br.com.testes.mybatis.model.Cliente;
import br.com.testes.mybatis.model.ClienteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int countByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int deleteByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int deleteByPrimaryKey(Integer idCliente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int insert(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int insertSelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    List<Cliente> selectByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    Cliente selectByPrimaryKey(Integer idCliente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByExampleSelective(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByExample(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByPrimaryKeySelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByPrimaryKey(Cliente record);
}