package br.com.testes.mybatis.dao;

import br.com.testes.mybatis.model.Cliente;
import br.com.testes.mybatis.model.ClienteExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ClienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @SelectProvider(type=ClienteSqlProvider.class, method="countByExample")
    int countByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @DeleteProvider(type=ClienteSqlProvider.class, method="deleteByExample")
    int deleteByExample(ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Delete({
        "delete from cliente",
        "where idcliente = #{idcliente,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idcliente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Insert({
        "insert into cliente (idcliente, nome, ",
        "telefone)",
        "values (#{idcliente,jdbcType=INTEGER}, #{nome,jdbcType=VARCHAR}, ",
        "#{telefone,jdbcType=VARCHAR})"
    })
    int insert(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @InsertProvider(type=ClienteSqlProvider.class, method="insertSelective")
    int insertSelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @SelectProvider(type=ClienteSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="idcliente", property="idcliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nome", property="nome", jdbcType=JdbcType.VARCHAR),
        @Result(column="telefone", property="telefone", jdbcType=JdbcType.VARCHAR)
    })
    List<Cliente> selectByExample(ClienteExample example);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Select({
        "select",
        "idcliente, nome, telefone",
        "from cliente",
        "where idcliente = #{idcliente,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="idcliente", property="idcliente", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nome", property="nome", jdbcType=JdbcType.VARCHAR),
        @Result(column="telefone", property="telefone", jdbcType=JdbcType.VARCHAR)
    })
    Cliente selectByPrimaryKey(Integer idcliente);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Select({
    	"select",
    	"idcliente, nome, telefone",
    	"from cliente"
    })
    List<Cliente> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @UpdateProvider(type=ClienteSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @UpdateProvider(type=ClienteSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Cliente record, @Param("example") ClienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @UpdateProvider(type=ClienteSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Cliente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Update({
        "update cliente",
        "set nome = #{nome,jdbcType=VARCHAR},",
          "telefone = #{telefone,jdbcType=VARCHAR}",
        "where idcliente = #{idcliente,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Cliente record);
}