package br.com.testes.mybatis.dao;

import br.com.testes.mybatis.model.Endereco;
import br.com.testes.mybatis.model.EnderecoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnderecoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int countByExample(EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int deleteByExample(EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int deleteByPrimaryKey(Integer idendereco);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int insert(Endereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int insertSelective(Endereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    List<Endereco> selectByExample(EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    Endereco selectByPrimaryKey(Integer idendereco);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByExampleSelective(@Param("record") Endereco record, @Param("example") EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByExample(@Param("record") Endereco record, @Param("example") EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByPrimaryKeySelective(Endereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    int updateByPrimaryKey(Endereco record);
}