package br.com.testes.mybatis.dao;

import br.com.testes.mybatis.model.Endereco;
import br.com.testes.mybatis.model.EnderecoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EnderecoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @SelectProvider(type=EnderecoSqlProvider.class, method="countByExample")
    int countByExample(EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @DeleteProvider(type=EnderecoSqlProvider.class, method="deleteByExample")
    int deleteByExample(EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Delete({
        "delete from endereco",
        "where idendereco = #{idendereco,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idendereco);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Insert({
        "insert into endereco (idendereco, rua, ",
        "bairro, cidade, ",
        "estado, pais, idcliente)",
        "values (#{idendereco,jdbcType=INTEGER}, #{rua,jdbcType=VARCHAR}, ",
        "#{bairro,jdbcType=VARCHAR}, #{cidade,jdbcType=VARCHAR}, ",
        "#{estado,jdbcType=VARCHAR}, #{pais,jdbcType=VARCHAR}, #{idcliente,jdbcType=INTEGER})"
    })
    int insert(Endereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @InsertProvider(type=EnderecoSqlProvider.class, method="insertSelective")
    int insertSelective(Endereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @SelectProvider(type=EnderecoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="idendereco", property="idendereco", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="rua", property="rua", jdbcType=JdbcType.VARCHAR),
        @Result(column="bairro", property="bairro", jdbcType=JdbcType.VARCHAR),
        @Result(column="cidade", property="cidade", jdbcType=JdbcType.VARCHAR),
        @Result(column="estado", property="estado", jdbcType=JdbcType.VARCHAR),
        @Result(column="pais", property="pais", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcliente", property="idcliente", jdbcType=JdbcType.INTEGER)
    })
    List<Endereco> selectByExample(EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Select({
        "select",
        "idendereco, rua, bairro, cidade, estado, pais, idcliente",
        "from endereco",
        "where idendereco = #{idendereco,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="idendereco", property="idendereco", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="rua", property="rua", jdbcType=JdbcType.VARCHAR),
        @Result(column="bairro", property="bairro", jdbcType=JdbcType.VARCHAR),
        @Result(column="cidade", property="cidade", jdbcType=JdbcType.VARCHAR),
        @Result(column="estado", property="estado", jdbcType=JdbcType.VARCHAR),
        @Result(column="pais", property="pais", jdbcType=JdbcType.VARCHAR),
        @Result(column="idcliente", property="idcliente", jdbcType=JdbcType.INTEGER)
    })
    Endereco selectByPrimaryKey(Integer idendereco);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @UpdateProvider(type=EnderecoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Endereco record, @Param("example") EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @UpdateProvider(type=EnderecoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Endereco record, @Param("example") EnderecoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @UpdateProvider(type=EnderecoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Endereco record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    @Update({
        "update endereco",
        "set rua = #{rua,jdbcType=VARCHAR},",
          "bairro = #{bairro,jdbcType=VARCHAR},",
          "cidade = #{cidade,jdbcType=VARCHAR},",
          "estado = #{estado,jdbcType=VARCHAR},",
          "pais = #{pais,jdbcType=VARCHAR},",
          "idcliente = #{idcliente,jdbcType=INTEGER}",
        "where idendereco = #{idendereco,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Endereco record);
}