package br.com.testes.mybatis.model;

public class Cliente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.idcliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private Integer idcliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.nome
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String nome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.telefone
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String telefone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.idcliente
     *
     * @return the value of cliente.idcliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.idcliente
     *
     * @param idcliente the value for cliente.idcliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.nome
     *
     * @return the value of cliente.nome
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.nome
     *
     * @param nome the value for cliente.nome
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setNome(String nome) {
        this.nome = nome == null ? null : nome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.telefone
     *
     * @return the value of cliente.telefone
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getTelefone() {
        return telefone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.telefone
     *
     * @param telefone the value for cliente.telefone
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setTelefone(String telefone) {
        this.telefone = telefone == null ? null : telefone.trim();
    }
}