package br.com.testes.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class ClienteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public ClienteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdClienteIsNull() {
            addCriterion("idCliente is null");
            return (Criteria) this;
        }

        public Criteria andIdClienteIsNotNull() {
            addCriterion("idCliente is not null");
            return (Criteria) this;
        }

        public Criteria andIdClienteEqualTo(Integer value) {
            addCriterion("idCliente =", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotEqualTo(Integer value) {
            addCriterion("idCliente <>", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteGreaterThan(Integer value) {
            addCriterion("idCliente >", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("idCliente >=", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteLessThan(Integer value) {
            addCriterion("idCliente <", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteLessThanOrEqualTo(Integer value) {
            addCriterion("idCliente <=", value, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteIn(List<Integer> values) {
            addCriterion("idCliente in", values, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotIn(List<Integer> values) {
            addCriterion("idCliente not in", values, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteBetween(Integer value1, Integer value2) {
            addCriterion("idCliente between", value1, value2, "idCliente");
            return (Criteria) this;
        }

        public Criteria andIdClienteNotBetween(Integer value1, Integer value2) {
            addCriterion("idCliente not between", value1, value2, "idCliente");
            return (Criteria) this;
        }

        public Criteria andNomeIsNull() {
            addCriterion("nome is null");
            return (Criteria) this;
        }

        public Criteria andNomeIsNotNull() {
            addCriterion("nome is not null");
            return (Criteria) this;
        }

        public Criteria andNomeEqualTo(String value) {
            addCriterion("nome =", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotEqualTo(String value) {
            addCriterion("nome <>", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeGreaterThan(String value) {
            addCriterion("nome >", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeGreaterThanOrEqualTo(String value) {
            addCriterion("nome >=", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLessThan(String value) {
            addCriterion("nome <", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLessThanOrEqualTo(String value) {
            addCriterion("nome <=", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLike(String value) {
            addCriterion("nome like", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotLike(String value) {
            addCriterion("nome not like", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeIn(List<String> values) {
            addCriterion("nome in", values, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotIn(List<String> values) {
            addCriterion("nome not in", values, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeBetween(String value1, String value2) {
            addCriterion("nome between", value1, value2, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotBetween(String value1, String value2) {
            addCriterion("nome not between", value1, value2, "nome");
            return (Criteria) this;
        }

        public Criteria andTelefoneIsNull() {
            addCriterion("telefone is null");
            return (Criteria) this;
        }

        public Criteria andTelefoneIsNotNull() {
            addCriterion("telefone is not null");
            return (Criteria) this;
        }

        public Criteria andTelefoneEqualTo(String value) {
            addCriterion("telefone =", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneNotEqualTo(String value) {
            addCriterion("telefone <>", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneGreaterThan(String value) {
            addCriterion("telefone >", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneGreaterThanOrEqualTo(String value) {
            addCriterion("telefone >=", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneLessThan(String value) {
            addCriterion("telefone <", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneLessThanOrEqualTo(String value) {
            addCriterion("telefone <=", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneLike(String value) {
            addCriterion("telefone like", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneNotLike(String value) {
            addCriterion("telefone not like", value, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneIn(List<String> values) {
            addCriterion("telefone in", values, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneNotIn(List<String> values) {
            addCriterion("telefone not in", values, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneBetween(String value1, String value2) {
            addCriterion("telefone between", value1, value2, "telefone");
            return (Criteria) this;
        }

        public Criteria andTelefoneNotBetween(String value1, String value2) {
            addCriterion("telefone not between", value1, value2, "telefone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cliente
     *
     * @mbggenerated do_not_delete_during_merge Sat May 03 22:23:59 BRT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}