package br.com.testes.mybatis.model;

public class Cliente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.idCliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private Integer idCliente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.nome
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private String nome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.telefone
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private String telefone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.idCliente
     *
     * @return the value of cliente.idCliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.idCliente
     *
     * @param idCliente the value for cliente.idCliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.nome
     *
     * @return the value of cliente.nome
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.nome
     *
     * @param nome the value for cliente.nome
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setNome(String nome) {
        this.nome = nome == null ? null : nome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.telefone
     *
     * @return the value of cliente.telefone
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public String getTelefone() {
        return telefone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.telefone
     *
     * @param telefone the value for cliente.telefone
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setTelefone(String telefone) {
        this.telefone = telefone == null ? null : telefone.trim();
    }
}