package br.com.testes.mybatis.model;

public class Endereco {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.idendereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private Integer idendereco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.rua
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private String rua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.bairro
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private String bairro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.municipio
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private String municipio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.idcliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    private Integer idcliente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.idendereco
     *
     * @return the value of endereco.idendereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public Integer getIdendereco() {
        return idendereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.idendereco
     *
     * @param idendereco the value for endereco.idendereco
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setIdendereco(Integer idendereco) {
        this.idendereco = idendereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.rua
     *
     * @return the value of endereco.rua
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public String getRua() {
        return rua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.rua
     *
     * @param rua the value for endereco.rua
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setRua(String rua) {
        this.rua = rua == null ? null : rua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.bairro
     *
     * @return the value of endereco.bairro
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public String getBairro() {
        return bairro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.bairro
     *
     * @param bairro the value for endereco.bairro
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setBairro(String bairro) {
        this.bairro = bairro == null ? null : bairro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.municipio
     *
     * @return the value of endereco.municipio
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public String getMunicipio() {
        return municipio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.municipio
     *
     * @param municipio the value for endereco.municipio
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setMunicipio(String municipio) {
        this.municipio = municipio == null ? null : municipio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.idcliente
     *
     * @return the value of endereco.idcliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.idcliente
     *
     * @param idcliente the value for endereco.idcliente
     *
     * @mbggenerated Sat May 03 22:23:59 BRT 2014
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
}