package br.com.testes.mybatis.model;

public class Endereco {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.idendereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private Integer idendereco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.rua
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String rua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.bairro
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String bairro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.cidade
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String cidade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.estado
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.pais
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private String pais;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endereco.idcliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    private Integer idcliente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.idendereco
     *
     * @return the value of endereco.idendereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public Integer getIdendereco() {
        return idendereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.idendereco
     *
     * @param idendereco the value for endereco.idendereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setIdendereco(Integer idendereco) {
        this.idendereco = idendereco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.rua
     *
     * @return the value of endereco.rua
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getRua() {
        return rua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.rua
     *
     * @param rua the value for endereco.rua
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setRua(String rua) {
        this.rua = rua == null ? null : rua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.bairro
     *
     * @return the value of endereco.bairro
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getBairro() {
        return bairro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.bairro
     *
     * @param bairro the value for endereco.bairro
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setBairro(String bairro) {
        this.bairro = bairro == null ? null : bairro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.cidade
     *
     * @return the value of endereco.cidade
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getCidade() {
        return cidade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.cidade
     *
     * @param cidade the value for endereco.cidade
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setCidade(String cidade) {
        this.cidade = cidade == null ? null : cidade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.estado
     *
     * @return the value of endereco.estado
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.estado
     *
     * @param estado the value for endereco.estado
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setEstado(String estado) {
        this.estado = estado == null ? null : estado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.pais
     *
     * @return the value of endereco.pais
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.pais
     *
     * @param pais the value for endereco.pais
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setPais(String pais) {
        this.pais = pais == null ? null : pais.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endereco.idcliente
     *
     * @return the value of endereco.idcliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endereco.idcliente
     *
     * @param idcliente the value for endereco.idcliente
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
}