package br.com.testes.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class EnderecoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public EnderecoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdenderecoIsNull() {
            addCriterion("idendereco is null");
            return (Criteria) this;
        }

        public Criteria andIdenderecoIsNotNull() {
            addCriterion("idendereco is not null");
            return (Criteria) this;
        }

        public Criteria andIdenderecoEqualTo(Integer value) {
            addCriterion("idendereco =", value, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoNotEqualTo(Integer value) {
            addCriterion("idendereco <>", value, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoGreaterThan(Integer value) {
            addCriterion("idendereco >", value, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoGreaterThanOrEqualTo(Integer value) {
            addCriterion("idendereco >=", value, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoLessThan(Integer value) {
            addCriterion("idendereco <", value, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoLessThanOrEqualTo(Integer value) {
            addCriterion("idendereco <=", value, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoIn(List<Integer> values) {
            addCriterion("idendereco in", values, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoNotIn(List<Integer> values) {
            addCriterion("idendereco not in", values, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoBetween(Integer value1, Integer value2) {
            addCriterion("idendereco between", value1, value2, "idendereco");
            return (Criteria) this;
        }

        public Criteria andIdenderecoNotBetween(Integer value1, Integer value2) {
            addCriterion("idendereco not between", value1, value2, "idendereco");
            return (Criteria) this;
        }

        public Criteria andRuaIsNull() {
            addCriterion("rua is null");
            return (Criteria) this;
        }

        public Criteria andRuaIsNotNull() {
            addCriterion("rua is not null");
            return (Criteria) this;
        }

        public Criteria andRuaEqualTo(String value) {
            addCriterion("rua =", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaNotEqualTo(String value) {
            addCriterion("rua <>", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaGreaterThan(String value) {
            addCriterion("rua >", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaGreaterThanOrEqualTo(String value) {
            addCriterion("rua >=", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaLessThan(String value) {
            addCriterion("rua <", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaLessThanOrEqualTo(String value) {
            addCriterion("rua <=", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaLike(String value) {
            addCriterion("rua like", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaNotLike(String value) {
            addCriterion("rua not like", value, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaIn(List<String> values) {
            addCriterion("rua in", values, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaNotIn(List<String> values) {
            addCriterion("rua not in", values, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaBetween(String value1, String value2) {
            addCriterion("rua between", value1, value2, "rua");
            return (Criteria) this;
        }

        public Criteria andRuaNotBetween(String value1, String value2) {
            addCriterion("rua not between", value1, value2, "rua");
            return (Criteria) this;
        }

        public Criteria andBairroIsNull() {
            addCriterion("bairro is null");
            return (Criteria) this;
        }

        public Criteria andBairroIsNotNull() {
            addCriterion("bairro is not null");
            return (Criteria) this;
        }

        public Criteria andBairroEqualTo(String value) {
            addCriterion("bairro =", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroNotEqualTo(String value) {
            addCriterion("bairro <>", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroGreaterThan(String value) {
            addCriterion("bairro >", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroGreaterThanOrEqualTo(String value) {
            addCriterion("bairro >=", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroLessThan(String value) {
            addCriterion("bairro <", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroLessThanOrEqualTo(String value) {
            addCriterion("bairro <=", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroLike(String value) {
            addCriterion("bairro like", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroNotLike(String value) {
            addCriterion("bairro not like", value, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroIn(List<String> values) {
            addCriterion("bairro in", values, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroNotIn(List<String> values) {
            addCriterion("bairro not in", values, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroBetween(String value1, String value2) {
            addCriterion("bairro between", value1, value2, "bairro");
            return (Criteria) this;
        }

        public Criteria andBairroNotBetween(String value1, String value2) {
            addCriterion("bairro not between", value1, value2, "bairro");
            return (Criteria) this;
        }

        public Criteria andCidadeIsNull() {
            addCriterion("cidade is null");
            return (Criteria) this;
        }

        public Criteria andCidadeIsNotNull() {
            addCriterion("cidade is not null");
            return (Criteria) this;
        }

        public Criteria andCidadeEqualTo(String value) {
            addCriterion("cidade =", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeNotEqualTo(String value) {
            addCriterion("cidade <>", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeGreaterThan(String value) {
            addCriterion("cidade >", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeGreaterThanOrEqualTo(String value) {
            addCriterion("cidade >=", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeLessThan(String value) {
            addCriterion("cidade <", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeLessThanOrEqualTo(String value) {
            addCriterion("cidade <=", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeLike(String value) {
            addCriterion("cidade like", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeNotLike(String value) {
            addCriterion("cidade not like", value, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeIn(List<String> values) {
            addCriterion("cidade in", values, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeNotIn(List<String> values) {
            addCriterion("cidade not in", values, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeBetween(String value1, String value2) {
            addCriterion("cidade between", value1, value2, "cidade");
            return (Criteria) this;
        }

        public Criteria andCidadeNotBetween(String value1, String value2) {
            addCriterion("cidade not between", value1, value2, "cidade");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("estado like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("estado not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andPaisIsNull() {
            addCriterion("pais is null");
            return (Criteria) this;
        }

        public Criteria andPaisIsNotNull() {
            addCriterion("pais is not null");
            return (Criteria) this;
        }

        public Criteria andPaisEqualTo(String value) {
            addCriterion("pais =", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotEqualTo(String value) {
            addCriterion("pais <>", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisGreaterThan(String value) {
            addCriterion("pais >", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisGreaterThanOrEqualTo(String value) {
            addCriterion("pais >=", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisLessThan(String value) {
            addCriterion("pais <", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisLessThanOrEqualTo(String value) {
            addCriterion("pais <=", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisLike(String value) {
            addCriterion("pais like", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotLike(String value) {
            addCriterion("pais not like", value, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisIn(List<String> values) {
            addCriterion("pais in", values, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotIn(List<String> values) {
            addCriterion("pais not in", values, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisBetween(String value1, String value2) {
            addCriterion("pais between", value1, value2, "pais");
            return (Criteria) this;
        }

        public Criteria andPaisNotBetween(String value1, String value2) {
            addCriterion("pais not between", value1, value2, "pais");
            return (Criteria) this;
        }

        public Criteria andIdclienteIsNull() {
            addCriterion("idcliente is null");
            return (Criteria) this;
        }

        public Criteria andIdclienteIsNotNull() {
            addCriterion("idcliente is not null");
            return (Criteria) this;
        }

        public Criteria andIdclienteEqualTo(Integer value) {
            addCriterion("idcliente =", value, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteNotEqualTo(Integer value) {
            addCriterion("idcliente <>", value, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteGreaterThan(Integer value) {
            addCriterion("idcliente >", value, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("idcliente >=", value, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteLessThan(Integer value) {
            addCriterion("idcliente <", value, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteLessThanOrEqualTo(Integer value) {
            addCriterion("idcliente <=", value, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteIn(List<Integer> values) {
            addCriterion("idcliente in", values, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteNotIn(List<Integer> values) {
            addCriterion("idcliente not in", values, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteBetween(Integer value1, Integer value2) {
            addCriterion("idcliente between", value1, value2, "idcliente");
            return (Criteria) this;
        }

        public Criteria andIdclienteNotBetween(Integer value1, Integer value2) {
            addCriterion("idcliente not between", value1, value2, "idcliente");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table endereco
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 26 22:49:00 BRT 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table endereco
     *
     * @mbggenerated Sat Apr 26 22:49:00 BRT 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}